#!/usr/bin/python 
from SimpleCV import *
from SimpleCV import RenderEngine

img = Image("../sampleimages/aerospace.jpg")
engine = DrawingLayer((img.width,img.height))
#engine.setDefaultAlpha(34)
a = (20,20)
b = (20,100)
c = (100,100)
d = (100,20)
engine.line(a,b,alpha=128,antialias=False,width=5)
engine.line(b,c,alpha=128,antialias=False)
engine.line(c,d)
engine.line(d,a)
engine.line(a,c)
engine.line(b,d,antialias=False,width=5)
a = (200,200)
b = (200,300)
c = (300,300)
d = (300,200)
pts = (a,b,c,d)
engine2 = DrawingLayer((img.width,img.height))
engine2.lines(pts,color=Color.AZURE)
img.addDrawingLayer(engine)
img.addDrawingLayer(engine2)
foo = img.drawLayers()
foo.save('nekkid_bea_arthur.png')
a = (10,10)
b = (30,30)
c = (10,50)
d = (50,50)
e = (70,70)
f = (50,60)
g = (40,40)
h = (40,30)
engine3 = DrawingLayer((img.width,img.height))
engine3.polygon((a,b,c,d,e,f,g,h),color=Color.RED,antialias=False)
engine3.circle((150,150),50,color=Color.VIOLET,filled=True)
engine3.circle((150,150),53,color=Color.AQUAMARINE,filled=False,width=3,antialias=False)
engine3.circle((150,150),15,color=Color.FUCHSIA,filled=True)
print(engine.listFonts())
f = engine.listFonts()
engine.selectFont(f[5])
engine.text("HERP-A-DERP",(40,140),color=Color.HOTPINK)
engine.setLayerAlpha(128)
img.addDrawingLayer(engine3)
img2 = img.drawLayers([0,2])

img2.save("ItWorks.jpg")