;; This buffer is for notes you don't want to save, and for Lisp evaluation.
;; If you want to create a file, visit that file with C-x C-f,
;; then enter the text in that file's own buffer.
img = Image("./SimpleCV/sampleimages/containment_test.png")
b = img.findBlobs()
l = img.findLines()
c = img.findCorners()
cr = img.findCircle(thresh=270)
l2 = l.above(b[-1])
l3 = l.below(b[-1])
l4 = l.right(b[-1])
l5 = l.left(b[-1])
l6 = l.inside(b[-1])
l7 = l.overlaps(b[-1])
l2.draw(color=Color.GREEN,width=3)
l3.draw(color=Color.RED,width=3)
l4.draw(color=Color.ORANGE,width=3)
l5.draw(color=Color.YELLOW,width=3)
l6.draw(color=Color.BLUE,width=3)
l7.draw(color=Color.VIOLET,width=3)
img.show()

img = Image("./SimpleCV/sampleimages/containment_test.png")
b = img.findBlobs()
l = img.findLines()
c = img.findCorners()
cr = img.findCircle(thresh=270)
l2 = l.above(b[-1])
l3 = l.below(b[-1])
l4 = l.right(b[-1])
l5 = l.left(b[-1])
#l6 = l.overlaps(b[-1],simple=False)
l7 = l.inside(b[-1],simple=False)
l2.draw(color=Color.GREEN,width=3)
l3.draw(color=Color.RED,width=3)
l4.draw(color=Color.ORANGE,width=3)
l5.draw(color=Color.YELLOW,width=3)
#l6.draw(color=Color.BLUE,width=3)
l7.draw(color=Color.VIOLET,width=3)
img.show()

img = Image("./SimpleCV/sampleimages/containment_test.png")
b = img.findBlobs()
l = img.findLines()
c = img.findCorners()
cr = img.findCircle(thresh=300)
l2 = cr.above(b[-1])
l3 = cr.below(b[-1])
l4 = cr.right(b[-1])
l5 = cr.left(b[-1])
l6 = cr.overlaps(b[-1],simple=False)
l7 = cr.inside(b[-1],simple=False)
l2.draw(color=Color.GREEN,width=3)
l3.draw(color=Color.RED,width=3)
l4.draw(color=Color.ORANGE,width=3)
l5.draw(color=Color.YELLOW,width=3)
l6.draw(color=Color.BLUE,width=3)
l7.draw(color=Color.VIOLET,width=3)
img.show()
 

img = Image("./SimpleCV/sampleimages/containment_test.png")
b = img.findBlobs()
l = img.findLines()
c = img.findCorners()
cr = img.findCircle(thresh=300)
l2 = cr.above(b[-1])
l3 = cr.below(b[-1])
l4 = cr.right(b[-1])
l5 = cr.left(b[-1])
l6 = cr.overlaps(b[-1],simple=True)
l7 = cr.inside(b[-1],simple=True)
l2.draw(color=Color.GREEN,width=3)
l3.draw(color=Color.RED,width=3)
l4.draw(color=Color.ORANGE,width=3)
l5.draw(color=Color.YELLOW,width=3)
l6.draw(color=Color.BLUE,width=3)
l7.draw(color=Color.VIOLET,width=3)
img.show()
